/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package system.edit;

import DknFile.Archivo;
import console.DknConsole;
import java.io.File;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import messages.VError;
import messages.VMessage;
import model.bank.BankAccount;
import model.bank.BankAccountDAO;
import model.bank.BankAccounts;
import model.bank.BankTransDAO;
import system.config.AppGlobal;
import system.type.Type;
import system.type.TypeDAO;

/**
 *
 * @author richneom
 */
public class PnlImpExcel extends javax.swing.JPanel {

    private boolean ok;
    private final WImpExcel wImpExcel;
    private File fileXls;
    private String fileNameXls;
    private int idBankAccount;
    private int rowsImported;
    
    /**
     * Creates new form PnlImpExcel
     * @param wImpExcel
     */
    public PnlImpExcel(WImpExcel wImpExcel) {
        initComponents();
        this.wImpExcel = wImpExcel;
        
        init();
    }
    
    private void init() {
        lblFileXls.setText(AppGlobal.getText("WIMPEXCEL_LBL_FILEXLS_TEXT") + ":");
        lblBankAccount.setText(AppGlobal.getText("WIMPEXCEL_LBL_BANKACCOUNT_TEXT") + ":");
        lblBank.setText(AppGlobal.getText("WIMPEXCEL_LBL_BANK_TEXT") + ":");
        lblBankAccountNumber.setText(AppGlobal.getText("WIMPEXCEL_LBL_BANKACCOUNTNUMBER_TEXT") + ":");
        
        btnOk.setText(AppGlobal.getText("WIMPEXCEL_BTN_OK_TEXT"));
        btnCancel.setText(AppGlobal.getText("WIMPEXCEL_BTN_CANCEL_TEXT"));
        
        txtFileXls.setText("");
        txtBank.setText("");
        txtBankAccountNumber.setText("");
        
        cmbBankAccount.removeAllItems();
        try {
            BankAccounts bankAccounts = BankAccountDAO.gets("name");
            for (BankAccount ba : bankAccounts) {
                cmbBankAccount.addItem(ba.getName());
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(PnlImpExcel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        this.ok = false;
        this.rowsImported = 0;
    }
    
    public boolean isOk() {
        return ok;
    }

    public int getRowsImported() {
        return rowsImported;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCancel = new javax.swing.JButton();
        btnOk = new javax.swing.JButton();
        lblFileXls = new javax.swing.JLabel();
        txtFileXls = new javax.swing.JTextField();
        btnFileXls = new javax.swing.JButton();
        lblBankAccount = new javax.swing.JLabel();
        cmbBankAccount = new javax.swing.JComboBox<>();
        txtBank = new javax.swing.JTextField();
        txtBankAccountNumber = new javax.swing.JTextField();
        lblBank = new javax.swing.JLabel();
        lblBankAccountNumber = new javax.swing.JLabel();

        btnCancel.setText("jButton1");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnOk.setText("jButton2");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        lblFileXls.setText("jLabel1");

        txtFileXls.setText("jTextField1");

        btnFileXls.setText("...");
        btnFileXls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFileXlsActionPerformed(evt);
            }
        });

        lblBankAccount.setText("jLabel1");

        cmbBankAccount.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbBankAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBankAccountActionPerformed(evt);
            }
        });

        txtBank.setEditable(false);
        txtBank.setText("jTextField1");

        txtBankAccountNumber.setEditable(false);
        txtBankAccountNumber.setText("jTextField2");

        lblBank.setText("jLabel2");

        lblBankAccountNumber.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnOk)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFileXls)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFileXls)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFileXls))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBankAccount)
                            .addComponent(lblBank)
                            .addComponent(lblBankAccountNumber))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtBank)
                                .addComponent(cmbBankAccount, 0, 200, Short.MAX_VALUE))
                            .addComponent(txtBankAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 247, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblBank, lblBankAccount, lblBankAccountNumber, lblFileXls});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFileXls)
                    .addComponent(txtFileXls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFileXls))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBankAccount)
                    .addComponent(cmbBankAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBank))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBankAccountNumber)
                    .addComponent(txtBankAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnOk))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        if (idBankAccount < 0) {
            VError.show(wImpExcel, "Seleccione una cuenta bancaria.");
        }
        else if (fileXls == null) {
            VError.show(wImpExcel, "Seleccione un archivo excel.");
        }
        else {
            this.ok = true;
        
            try {
                rowsImported = BankTransDAO.importExcel(idBankAccount, fileXls);
            } catch (ClassNotFoundException | SQLException ex) {
                DknConsole.error(Thread.currentThread().getStackTrace()[1].toString(), "Hubo un error y no se puedo importar los datos");
                Logger.getLogger(PnlImpExcel.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            VMessage.show(wImpExcel, "Registros importados: " + rowsImported);
            
            wImpExcel.dispose();
        }
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.ok = false;
        this.rowsImported = 0;
        
        wImpExcel.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnFileXlsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFileXlsActionPerformed
        fileXls = Archivo.obtenerArchivo(wImpExcel, ".xls", AppGlobal.getDirWorking(), Archivo.OpenMode.READ);
        
        if (fileXls != null) {
            AppGlobal.setDirWorking(Archivo.getRuta(fileXls));
            txtFileXls.setText(fileXls.getAbsolutePath());
            fileNameXls = fileXls.getAbsolutePath();
        }
    }//GEN-LAST:event_btnFileXlsActionPerformed

    private void cmbBankAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBankAccountActionPerformed
        String accountName = (String) cmbBankAccount.getSelectedItem();
        
        if (accountName != null && !accountName.isEmpty()) {
            try {
                BankAccount bankAccount = BankAccountDAO.get("name", accountName);

                txtBankAccountNumber.setText(bankAccount.getNumber());
                Type bank = TypeDAO.get("banks", bankAccount.getIdBank());
                if (bank != null) {
                    txtBank.setText(bank.getName());
                }
                idBankAccount = bankAccount.getId();
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(PnlImpExcel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_cmbBankAccountActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnFileXls;
    private javax.swing.JButton btnOk;
    private javax.swing.JComboBox<String> cmbBankAccount;
    private javax.swing.JLabel lblBank;
    private javax.swing.JLabel lblBankAccount;
    private javax.swing.JLabel lblBankAccountNumber;
    private javax.swing.JLabel lblFileXls;
    private javax.swing.JTextField txtBank;
    private javax.swing.JTextField txtBankAccountNumber;
    private javax.swing.JTextField txtFileXls;
    // End of variables declaration//GEN-END:variables
}
