/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package system.config.view;

import javax.swing.table.DefaultTableModel;
import system.config.AppConfig;
import system.config.ConfigData;

/**
 *
 * @author DickNeoM
 */
public class PnlConfigDataList extends javax.swing.JPanel {

    private final DefaultTableModel modelo;

    /**
     * Creates new form PnlConfigDataList
     */
    public PnlConfigDataList() {
        initComponents();
        
        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        
        modelo = (DefaultTableModel) tblConfigData.getModel();
        modelo.setColumnCount(0);
        modelo.addColumn("Codigo");
        modelo.addColumn("Titulo");
        modelo.addColumn("Categoria");
        modelo.addColumn("Tipo");
        modelo.addColumn("Valor");

        Object[] fila;
        modelo.setRowCount(0);
        for (ConfigData g : ConfigData.values()) {
//            System.out.println(g + " = " + String.valueOf(AppConfig.get(g)));
            
            fila = new Object[5];
            
            fila[0] = g;
            fila[1] = g.getTitle();
            fila[2] = g.getCategory();
            fila[3] = g.getType();
            fila[4] = AppConfig.get(g);
            
            modelo.addRow(fila);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblConfigData = new javax.swing.JTable();

        tblConfigData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblConfigData);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblConfigData;
    // End of variables declaration//GEN-END:variables
}
