/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package system.config.view;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import system.config.AppConfig;
import system.config.AppGlobal;
import system.config.ConfigData;

/**
 *
 * @author DickNeoM
 */
public class PnlConstantes extends javax.swing.JPanel {

    /**
     * Creates new form PnlConstantes
     */
    public PnlConstantes() {
        initComponents();
        
        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        
        btnSave.setText(AppGlobal.getText("WOPTIONS_BTN_SAVE"));
        
        lblIVA.setText(AppGlobal.getText(ConfigData.IVA_PORCENTAJE.getTitle()) + ":");
        
        fill();
    }

    private void fill() {
        txtIVA.setText(AppGlobal.getFormatDecimalShort().format(AppConfig.getDouble(ConfigData.IVA_PORCENTAJE)));
    }
    
    private void save() {
        double valor = Double.parseDouble(txtIVA.getText().trim());
        AppConfig.set(ConfigData.IVA_PORCENTAJE, valor);
        
        try {
            AppConfig.save();
            
            JOptionPane.showMessageDialog(this, AppGlobal.getText("WOPTIONS_MSG_SAVED_TEXT"), AppGlobal.getText("WOPTIONS_MSG_SAVED_TITLE"), JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException ex) {
            Logger.getLogger(PnlApariencia.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, AppGlobal.getText("WOPTIONS_MSG_NOSAVED_TEXT"), AppGlobal.getText("WOPTIONS_MSG_NOSAVED_TITLE"), JOptionPane.WARNING_MESSAGE);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSave = new javax.swing.JButton();
        lblIVA = new javax.swing.JLabel();
        txtIVA = new javax.swing.JTextField();

        btnSave.setText("jButton1");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblIVA.setText("jLabel1");

        txtIVA.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtIVA.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIVA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIVA, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(265, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIVA)
                    .addComponent(txtIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 232, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        save();
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lblIVA;
    private javax.swing.JTextField txtIVA;
    // End of variables declaration//GEN-END:variables
}
