/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package system.config.view;

import system.config.AppGlobal;

/**
 *
 * @author richneom
 */
public class PnlEditOptions extends javax.swing.JPanel {

    private final WEditOptions wOptions;

    /**
     * Creates new form PnlEditOptions
     * @param wOptions
     */
    public PnlEditOptions(WEditOptions wOptions) {
        initComponents();
        this.wOptions = wOptions;
        
        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        
        btnClose.setText(AppGlobal.getText("WOPTIONS_BTN_CLOSE"));
        
        pnlTab.add(new PnlApariencia(), AppGlobal.getText("WOPTIONS_PNL_APARIENCIA_TAB"));
        pnlTab.add(new PnlConstantes(), AppGlobal.getText("WOPTIONS_PNL_CONSTANTES_TAB"));
        pnlTab.add(new PnlDatos(), AppGlobal.getText("WOPTIONS_PNL_DATA_TAB"));
        pnlTab.add(new PnlConfigDataList(), AppGlobal.getText("WOPTIONS_PNL_CONFIG_DATA_TAB"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTab = new javax.swing.JTabbedPane();
        btnClose = new javax.swing.JButton();

        btnClose.setText("jButton1");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(294, Short.MAX_VALUE)
                .addComponent(btnClose)
                .addContainerGap())
            .addComponent(pnlTab, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlTab, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClose)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        wOptions.close();
    }//GEN-LAST:event_btnCloseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JTabbedPane pnlTab;
    // End of variables declaration//GEN-END:variables
}
